services:
  postgres:
    image: postgres
    container_name: semdin.com
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: semdincom
    ports:
      - "7777:5432" # Map external port 7777 to internal port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@semdin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:80"
    volumes:
      - ./pgdata:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
